name: Test Variable - GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Echo variable
        run: echo ${{ vars.var_test}}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MYSECRET'
          value: 'test1'
          repository: JoeHO888/test-github-action-secret
          token: ${{ secrets.TOKEN }}
  Job2:
    needs: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3    
      - run: echo ${{ secrets.MYSECRET }} | sed 's/./& /g'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
