name: Test Variable - GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.DUMMY_SECRET }}
      TEST_ENV_VAR: tjs
    steps:
      - run: echo "$TEST_SECRET"
      - run: echo "$TEST_ENV_VAR"
      - run: echo "$TEST_SECRET asd" | sed 's/./& /g
